### ISSUE TITLE
filename mismatch of RollershutterItem.js

### ISSUE THREAD

**Issue by gretel** [redhell/homebridge-openHAB#1]
actually it is named `RollerShutterItem.js` which makes it fail on OS with case-sensitive filesystem:

```
Jan 28 22:56:38 DietPi node[20288]: ====================
Jan 28 22:56:38 DietPi node[20288]: ERROR LOADING PLUGIN homebridge-openhab:
Jan 28 22:56:38 DietPi node[20288]: Error: Cannot find module '../items/RollershutterItem.js'
Jan 28 22:56:38 DietPi node[20288]: at Function.Module._resolveFilename (module.js:326:15)
Jan 28 22:56:38 DietPi node[20288]: at Function.Module._load (module.js:277:25)
Jan 28 22:56:38 DietPi node[20288]: at Module.require (module.js:354:17)
Jan 28 22:56:38 DietPi node[20288]: at require (internal/module.js:12:17)
Jan 28 22:56:38 DietPi node[20288]: at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-openhab/libs/ItemFactory.js:9:29)
Jan 28 22:56:38 DietPi node[20288]: at Module._compile (module.js:398:26)
Jan 28 22:56:38 DietPi node[20288]: at Object.Module._extensions..js (module.js:405:10)
Jan 28 22:56:38 DietPi node[20288]: at Module.load (module.js:344:32)
Jan 28 22:56:38 DietPi node[20288]: at Function.Module._load (module.js:301:12)
Jan 28 22:56:38 DietPi node[20288]: at Module.require (module.js:354:17)
```

solution is to rename the file to `RollershutterItem.js`.

**Comment by redhell** [comment]
Open an issue in the original repo.

**Comment by redhell** [comment]
Fixed with #ad01641

**Comment by gretel** [comment]
@redhell this bug does not occur using the 'original' repos code. additionally, your reference of '#ad0164' does point nowhere.

**Comment by gretel** [comment]
i'd be glad if this could be fixed. it's just a filename.

**Comment by redhell** [comment]
Try the upstream branch. There is a working thermostat item.
